require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "spec/**/*_spec.rb"
    - "test/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "config/**/*"
    - "bin/*"
    - "vendor/*"
    - "node_modules/*"
    - "tmp/*"
    - "log/*"
    - "coverage/*"
    - "config/initializers/*"
  TargetRubyVersion: 3.1.2

Style/Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Exclude:
    - "app/models/category.rb"
    - "app/models/dish.rb"

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - "app/models/state.rb"
    - "app/models/dish.rb"
    - "app/models/category.rb"

RSpec/MultipleExpectations:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - "db/seeds.rb"
